config/routes.rb
NinetyCats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      post 'accept'
      post 'deny'
    end
  end
  root to: "cats#index"

  resources :users, :only => [:new, :create, :show]
  resource :sessions
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex

  COLORS = %w( white black red green blue )

  validates :age, :birth_date, :color, :name, :sex, :presence => true
  validates :sex, :inclusion => %w( m f )
  validates :color, :inclusion => COLORS


  has_many(
    :rental_requests,
    :class_name => "CatRentalRequest",
    :foreign_key => :cat_id,
    :primary_key => :id,
    :dependent => :destroy
  )

  belongs_to(
    :owner,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  STATUSES = %w(PENDING APPROVED DENIED)

  validates :cat_id, :start_date, :end_date, :status, :presence => true
  validates :status, :inclusion => STATUSES
  validate :no_double_booking


  before_validation :set_status

  belongs_to(
    :cat,
    :class_name => "Cat",
    :foreign_key => :cat_id,
    :primary_key => :id
  )

  def overlapping_requests
    where_cond = <<-SQL
    (cat_id == :cat_id) AND ((end_date BETWEEN :start_date AND :end_date ) OR (start_date BETWEEN :end_date AND :start_date))
    SQL

    CatRentalRequest.where(where_cond, {cat_id: cat_id, start_date: start_date, end_date: end_date} )
  end

  def overlapping_approved_requests
    overlapping_requests.select do |request|
      request.status == "APPROVED" && request.id != self.id
    end
  end

  def overlapping_pending_requests
    overlapping_requests.select do |request|
      request.status == "PENDING" && request.id != self.id
    end
  end

  def no_double_booking
    error.add(:base, "Can't double book a cat") unless overlapping_approved_requests.empty?
  end

  def pending?
    self.status == "PENDING"
  end

  def approve!
    transaction do
      self.status = "APPROVED"
      self.save!
      overlapping_pending_requests.each do |req|
        req.deny!
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end


  def set_status
    self.status ||= "PENDING"
  end


end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :password, :user_name

  validates :password_digest, :user_name, :session_token, :presence => true

  before_validation :ensure_session_token

  has_many(
    :cats,
    :class_name => "Cat",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    user if !user.nil? && user.is_password?(password)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


  def generate_session_token
    SecureRandom.base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :ensure_owner, :only => [:accept, :deny]


  def create
    p "PARAMS"
    p params[:rental_requests]
    rental_request = CatRentalRequest.new(params[:rental_requests])

    if rental_request.save!
      redirect_to cat_url(params[:rental_requests][:cat_id])
    else
      render :text => "ERROR: Not a valid request"
    end
  end

  def accept
    req_approve = CatRentalRequest.find(params[:id])
    req_approve.approve!
    redirect_to req_approve.cat

    render :text => params
  end

  def deny
    req_deny = CatRentalRequest.find(params[:id])
    req_deny.deny!
    redirect_to cat_url(req_deny.cat.id)
  end

  def new

  end

  def ensure_owner
    rental = CatRentalRequest.find(params[:id])
    if !current_user.nil? && current_user.id == rental.cat.owner.id
      return true
    else
      redirect_to new_sessions_url
    end
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :ensure_owner, :only => [:edit, :update]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def create
    cat = Cat.new(params[:cat])
    cat.user_id = current_user.id

    if cat.save!
      redirect_to cat_url(cat)
    else
      render :text => "ERROR: Cat can't be saved!"
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def update
    cat = Cat.find(params[:id])

    if cat.update_attributes(params[:cat])
      redirect_to cat_url(cat)
    else
      render :text => "ERROR: Can't update cat!"
    end
  end

  def ensure_owner
    cat = Cat.find(params[:id])
    if !current_user.nil? && current_user.id == cat.owner.id
      return true
    else
      redirect_to new_sessions_url
    end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      log_in(user)

      redirect_to cats_url
    end
  end

  def destroy
    logout_current_user

    redirect_to new_sessions_url
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    new_user = User.new(params[:user])

    if new_user.save!
      log_in(new_user)
      redirect_to user_url(new_user)
    else
      render :text => "User NOT Saved"
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def log_in(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_path %>" method="POST">


  <label for="cat_color">Cat</label>
  <select name="rental_requests[cat_id]">
    <% Cat.all.each do |cat| %>
      <option value="<%=cat.id%>"><%=cat.name.upcase%></option>
    <% end %>
   </select>
  <p>

  <label for="request_start_date">Start Date</label>
  <input type="date" id="request_start_date" name="rental_requests[start_date]">
  <p>

  <label for="request_end_date">End Date</label>
  <input type="date" id="request_end_date" name="rental_requests[end_date]">
  <p>

  <input type="submit" value="REQUEST!">

</form>

app/views/cats/_form.html.erb
<% action_url = (@cat.persisted? ? cat_url(@cat) : cats_url) %>
<% method = (@cat.persisted? ? :put : :post) %>
<% action = (@cat.persisted? ? "EDIT!" : "MAKE!") %>

<form action="<%= action_url %>" method="POST">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="<%= method %>">


  <label for="cat_name">Name</label>
  <input type="text" id="cat_name" name="cat[name]" value="<%= @cat.name %>">
  <br>

  <label for="cat_age">Age</label>
  <input type="text" id="cat_age" name="cat[age]" value="<%= @cat.age %>">
  <br>

  <label for="cat_birth_date">Birth Date</label>
  <input type="date" id="cat_birth_date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br>

  <input type="radio" id="cat_sex_m" name="cat[sex]" value="m"
  <%= @cat.sex == "m" ? "checked" : "" %> >
  <label>Male</label>

  <input type="radio" id="cat_sex_f" name="cat[sex]" value="f"
    <%= @cat.sex == "f" ? "checked" : "" %> >
  <label>Female</label>
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]">
    <% Cat::COLORS.each do |color| %>
      <option value="<%=color%>"
        <%= @cat.color == color ? "selected" : "" %> > <%=color.upcase%>
      </options>
    <% end %>
 </select>

  <input type="submit" value="<%= action %>">
</form>

app/views/cats/edit.html.erb
<%= render "form" %>

app/views/cats/index.html.erb
<h3>All Cats</h3>

<% @cats.each do |cat| %>
  <%= link_to cat.name, cat_url(cat)%> <br>
<% end %>

app/views/cats/new.html.erb
<%= render "form" %>

app/views/cats/show.html.erb
<table>
  <tr>
    <th> Name </th>
    <th> Age </th>
    <th> Color </th>
    <th> Sex </th>
    <th> Birth Date </th>
  </tr>
  <tr>
    <td> <%=@cat.name%> </td>
    <td> <%=@cat.age%> </td>
    <td> <%=@cat.color%> </td>
    <td> <%=@cat.sex%> </td>
    <td> <%=@cat.birth_date%> </td>
  </tr>
</table>
<p>

<table>
  <tr>
    <td>Start Date</td>
    <td>End Date</td>
    <td>Status</td>
  </tr>

  <% @cat.rental_requests.order('start_date').each do |req| %>
    <tr>
      <td><%= req.start_date %></td>
      <td><%= req.end_date %></td>
      <td><%= req.status %></td>
      <td><%= button_to "Accept", accept_cat_rental_request_url(req) %> </td>
      <td><%= button_to "Deny", deny_cat_rental_request_url(req) %> </td>
    </tr>
  <% end %>
</table>

<%= link_to "Request rental", new_cat_rental_request_url(cat:@cat)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyCats</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= link_to "Home", :root, :method =>:get%>

  <% if current_user.nil? %>
    <%= button_to "Log in", new_sessions_url, :method => "get" %>
  <% else %>
    <%= link_to current_user.user_name, user_url(current_user), :method => :get%>
    <%= button_to "Log Out", sessions_url, :method => "delete" %>

  <%= link_to "List Cat", new_cat_url, :method => :get %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action="/users" method="POST">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="user_name">User Name</label>
  <input id="user_name" name="user[user_name]" type="text">
  <br>

  <label for="user_password">Password</label>
  <input id="user_password" name="user[password]" type="password">
  <br>

  <input type="submit" value="CREATE!">
</form>

app/views/users/show.html.erb
<h1>Hi <em><%= @user.user_name.capitalize %></em> !</h1>

<% @user.cats.each do |cat| %>

<%= link_to cat.name, cat_url(cat) %>
<% end %>